#pragma once

#define SETTINGS_INPUT_FILES "InputFiles"
#define SETTINGS_HBR "HardBodyRadius"
#define SETTINGS_EPOCH_INDEX "EpochIndex"
#define SETTINGS_SCENE_LOOKATCOM "Scene/LookAtCOM"
#define SETTINGS_SCENE_AUTOSCALE "Scene/AutoScale"
#define SETTINGS_SCENE_ALLTOALL "Scene/AllToAll"

#define UNIFORM_GLOBAL_VIEWPORTSIZE "uViewportSize"
#define UNIFORM_GLOBAL_PROJECTIONMATRIX "uProjectionMatrix"
#define UNIFORM_GLOBAL_MODELVIEWMATRIX "uModelviewMatrix"
#define UNIFORM_GLOBAL_BASECOLOR "uBaseColor"

#define ATTRIBUTE_GLOBAL_VERTEX "aVertex"
#define ATTRIBUTE_GLOBAL_COLOR "aColor"
#define ATTRIBUTE_GLOBAL_NORMAL "aNormal"
#define ATTRIBUTE_GLOBAL_TEXCOORDS "aTexCoords"

#define UNIFORM_WORLD_CAMERAPOSITION "uCamPos_WS"
#define UNIFORM_WORLD_LIGHTDIRECTION "uLight.Dir_WS"
#define UNIFORM_WORLD_LIGHTAMBIENT "uLight.Ambient"
#define UNIFORM_WORLD_LIGHTDIFFUSE "uLight.Diffuse"
#define UNIFORM_WORLD_LIGHTSPECULAR "uLight.Specular"
#define UNIFORM_WORLD_LIGHTSPECULARINTENSITY "uLight.SpecularIntensity"

#define UNIFORM_COMMON_MODELMATRIX "uModelMatrix"
#define UNIFORM_COMMON_NORMALMATRIX "uNormalMatrix"